### ISSUE TITLE
KenLMRunner raise java.lang.UnsatisfiedLinkError: no kenlm-jni in java.library.path

### ISSUE THREAD

**Issue by s-natsubori** [WorksApplications/uzushio#37]
I try to run `KenLMRunner` , it raise following error.

## Spark Submit
```
spark-submit \
    --class com.worksap.nlp.uzushio.lib.runners.KenLMRunner \
    --master='local[1]' \
    --conf spark.sql.parquet.columnarReaderBatchSize=512 \
    --conf spark.executor.extraLibraryPath=/usr/local/spark/jars \
    --conf spark.driver.extraLibraryPath=/usr/local/spark/jars \
    /usr/local/spark/jars/uzushio-assembly-0.1.0-SNAPSHOT.jar \
    --input=/opt/spark/work-dir/text/cc_0/language=ja \
    --output=/opt/spark/work-dir/filtered_cc/hash \
    --kenlm-model=/opt/spark/work-dir/kenlm/data/lm_sp/ja.arpa.bin \
    --sudachi-dict=/opt/spark/work-dir/sudachi/system_full.dic \
```

## Error
```
Caused by: java.lang.UnsatisfiedLinkError: no kenlm-jni in java.library.path: [/usr/local/spark/jars, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.jbaiter.kenlm.util.KenLMLoader.loadNativeLibrary(KenLMLoader.java:159)
        at com.github.jbaiter.kenlm.util.KenLMLoader.load(KenLMLoader.java:137)
        at com.github.jbaiter.kenlm.Model.<clinit>(Model.java:19)
        at com.worksap.nlp.uzushio.lib.resources.KenLM$.create(CachedLocalResource.scala:46)
        at com.worksap.nlp.uzushio.lib.resources.KenLM$.create(CachedLocalResource.scala:45)
        at com.worksap.nlp.uzushio.lib.resources.CachedLocalResource.$anonfun$get$3(CachedLocalResource.scala:22)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at com.worksap.nlp.uzushio.lib.resources.CachedLocalResource.get(CachedLocalResource.scala:22)
        at com.worksap.nlp.uzushio.lib.resources.CachedLocalResource.get$(CachedLocalResource.scala:15)
        at com.worksap.nlp.uzushio.lib.resources.KenLM$.get(CachedLocalResource.scala:45)
        at com.worksap.nlp.uzushio.lib.filters.KenLMEvaluator.<init>(KenLMDocAvgPerplexity.scala:49)
        at com.worksap.nlp.uzushio.lib.filters.KenLMEvaluatorNoOutliers.<init>(KenLMDocAvgPerplexity.scala:118)
        at com.worksap.nlp.uzushio.lib.filters.KenLMEvaluator$.make(KenLMDocAvgPerplexity.scala:112)
        at com.worksap.nlp.uzushio.lib.runners.KenLMRunner$LMPerplexity.evaluator$lzycompute(KenLMRunner.scala:26)
        at com.worksap.nlp.uzushio.lib.runners.KenLMRunner$LMPerplexity.evaluator(KenLMRunner.scala:26)
        at com.worksap.nlp.uzushio.lib.runners.KenLMRunner$LMPerplexity.process(KenLMRunner.scala:29)
        at com.worksap.nlp.uzushio.lib.runners.KenLMRunner$LMPerplexity.$anonfun$asUdf$1(KenLMRunner.scala:33)
        at com.worksap.nlp.uzushio.lib.runners.KenLMRunner$LMPerplexity.$anonfun$asUdf$1$adapted(KenLMRunner.scala:33)
```

## in /spark-config/abci-f/spark-defaults.conf
```
spark.executor.extraLibraryPath /groups/gcf51199/native-libs
spark.driver.extraLibraryPath /groups/gcf51199/native-libs
```
what is in `native-libs`?
Do I need any additional jars?

**Comment by eiennohito** [comment]
Sorry for the lack of docs for this, you need to compile native library for https://github.com/eiennohito/kenlm-java (and exactly this fork of kenlm-java) for LM-based filtering to work. I will add the documentation before ANLP2024.

**Comment by s-natsubori** [comment]
thank you for your reply!
I'll try!

**Comment by s-natsubori** [comment]
It seems to have worked. thank you.
Please enjoy ANLP2024!

**Comment by s-natsubori** [comment]
share my builder dockerfile for ref

Dockerfile
```
FROM maven:3.8.6-openjdk-11-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential libboost-all-dev zlib1g-dev libbz2-dev liblzma-dev \
    cmake \
    g++  \
    git \
    swig \
    wget \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# make dest dir
WORKDIR /work/dest
# build kenlm
WORKDIR /work/build_kenlm
RUN wget https://kheafield.com/code/kenlm.tar.gz -O kenlm.tar.gz && tar -xvzf kenlm.tar.gz  
RUN mkdir kenlm/build \
    && cd kenlm/build \
    && cmake .. \
    && make -j2 \
    && make install

# build kenlm-java
ENV CPATH=$JAVA_HOME/include:$JAVA_HOME/include/:$JAVA_HOME/include/linux:/work/build_kenlm/kenlm
RUN git clone https://github.com/eiennohito/kenlm-java 
RUN cd kenlm-java \
    && ./build.sh \
    && cp libkenlm-jni.so $JAVA_HOME/lib/ \
    && mvn package -Dmaven.javadoc.skip=true \
    && cp target/*.jar /work/dest/ \
    && cp libkenlm-jni.so /work/dest/

# build uzushio
WORKDIR /work/build_uzushio
ARG SBT_URL="https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.zip"
RUN wget ${SBT_URL} -O sbt.zip && unzip sbt.zip && cp sbt/bin/* /usr/local/bin/

RUN git clone https://github.com/WorksApplications/uzushio
RUN cd uzushio \
  && sbt assembly \
  && cp core/target/scala-2.12/*.jar /work/dest/

# WORKDIR /work/dest/
CMD ["tail", "-f", "/dev/null"]
```

build and copy
build_uzushio.sh
```
dest_to=./spark/jars/

docker build -t uzushio/uzushio-build .
run_id=`docker create uzushio/uzushio-build`
docker cp $run_id:/work/dest/ $dest_to
docker rm $run_id
```
